version: '3'

services:
  database:
    image: postgres
    env_file: [database.env]
    volumes: [database-data:/var/lib/postgresql/data/]
    ports: ["5432:5432"]
    networks: [intranet]
  application:
    links: [database:postgres]
    image: servian/techchallengeapp:latest
    ports: ["80:3000"]
    networks: [intranet]

volumes:
  database-data:

networks:
  intranet:
    driver: bridge
